### ISSUE TITLE
Build failed because of argon2 dependency

### ISSUE THREAD

**Issue by marcushohlbein** [tlebeitsuk/nuxt-cloudflare-lucia#3]
Hey,

tried to deploy to Cloudflare Pages, but get a failing build because of the argon2 dependency. Any idea how to solve this?

used Node 20.11.0

```
00:37:08.701 | [error] [nitro] Error: Cannot resolve "./argon2.win32-arm64-msvc.node" from "/opt/buildhome/repo/node_modules/.pnpm/@node-rs+argon2@1.7.0/node_modules/@node-rs/argon2/index.js" and externals are not allowed!
-- | --
00:37:08.702 |  
00:37:08.702 |  
00:37:08.703 | undefined
00:37:08.703 | [error] Cannot resolve "./argon2.win32-arm64-msvc.node" from "/opt/buildhome/repo/node_modules/.pnpm/@node-rs+argon2@1.7.0/node_modules/@node-rs/argon2/index.js" and externals are not allowed!
00:37:08.703 | at Object.resolveId (node_modules/.pnpm/nitropack@2.8.1/node_modules/nitropack/dist/shared/nitro.4ea992bc.mjs:1973:17)
00:37:08.704 | at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.10.0/node_modules/rollup/dist/es/shared/node-entry.js:18631:28)
00:37:08.704 | at async resolveId (node_modules/.pnpm/rollup@4.10.0/node_modules/rollup/dist/es/shared/node-entry.js:17298:26)
00:37:08.704 | at async ModuleLoader.resolveId (node_modules/.pnpm/rollup@4.10.0/node_modules/rollup/dist/es/shared/node-entry.js:17712:15)
00:37:08.704 | at async node_modules/.pnpm/@rollup+plugin-commonjs@25.0.7_rollup@4.10.0/node_modules/@rollup/plugin-commonjs/dist/es/index.js:785:16
00:37:08.704 | at async Promise.all (index 11)
00:37:08.704 | at async node_modules/.pnpm/@rollup+plugin-commonjs@25.0.7_rollup@4.10.0/node_modules/@rollup/plugin-commonjs/dist/es/index.js:777:32
00:37:08.705 | at async rewriteRequireExpressionsAndGetImportBlock (node_modules/.pnpm/@rollup+plugin-commonjs@25.0.7_rollup@4.10.0/node_modules/@rollup/plugin-commonjs/dist/es/index.js:1354:28)
00:37:08.705 | at async transformCommonjs (node_modules/.pnpm/@rollup+plugin-commonjs@25.0.7_rollup@4.10.0/node_modules/@rollup/plugin-commonjs/dist/es/index.js:1928:23)
00:37:08.705 | at async transform (node_modules/.pnpm/rollup@4.10.0/node_modules/rollup/dist/es/shared/node-entry.js:17630:16)
00:37:08.705 |  
00:37:08.705 | [error] Cannot resolve "./argon2.win32-arm64-msvc.node" from "/opt/buildhome/repo/node_modules/.pnpm/@node-rs+argon2@1.7.0/node_modules/@node-rs/argon2/index.js" and externals are not allowed!

```

**Comment by jamaluddinrumi** [comment]
will it gonna be working by replacing `Argon2id` with `Scrypt`?

![Screenshot 2024-03-19 at 02 47 00](https://github.com/tlebeitsuk/nuxt-cloudflare-lucia/assets/446780/94448a7e-1fee-49fd-9564-13808405d236)

https://lucia-auth.com/tutorials/username-and-password/astro

**Comment by jamaluddinrumi** [comment]
see also https://github.com/lucia-auth/lucia/issues/1460#issuecomment-1964928379

**Comment by tlebeitsuk** [comment]
I've now replaced Argon2id with Scrypt. Thanks!
